#+TITLE: calleha's website
#+AUTHOR: calleha
#+OPTIONS: num:nil line-break:t
#+HTML_HEAD: <style type="text/css">body{ max-width:65%; margin: auto; background-color: black; color: white; }</style>
#+HTML_HEAD: <style>.figure-number { display: none; }</style>

** De impetibus terroris
Europa America Septentrionalisque jam anno 2023 vixerant trans impetibus terroris multis, itaque nuntii impetus alterius non me obstupuerunt. Difficilis mihi fuit miseriam diei unius audire, quando sunt alii quos existentia cuotidiana cuia est miseria, quia vita cuotidiana suia est bellum vel genocidium. Spes mea est ut dies augendi voces imperatorum et ut dies tacendi voces populorum finiant.

8 December 2024, 22:18

** Anarchism or Marxist Leninism -- Should the approach be focused on ideological purity, or should the most pragmatic option be picked according to the opportunities presented?
I am a communist. I do not let the label dictate for me what my stance should be however. But I often ask myself this question and I invite anyone reading this to also ask themselves: Would I be a benevolent communist dictator? Or would the power of the state corrupt me, just as it seems to corrupt everybody else? If the answer to that question is no, however improbable that may seem, the even bigger question that follows is what would happen after my death. Is the dictatorship of the proletariat the true goal of Marxist Leninists? Could the anarcho-communist dream be acheived and also kept if unity is not a given? Where is the power to fight against external forces in a stateless society surrounded by nation states and capital holders? Are we doomed to never escape dictatorship? I do not currently have the answers to these questions.

25 November 2024, 14:09

** so I guess I'm gonna turn this into a blog thing for now. let me present myself
Quid est nomen mihi? Carl Hårleman, like many before me. If you type my name into a search engine, you'll find an 18th century architect whom I made a little website about as a work project. The site can be found at harleman.se, for those who might be curious to read about history and the Swedish nobility. I for one don't have much interest in trying to understand history from the perspective of the most privileged. And for how much information there seems to be documented about my ancestors, the information regarding the women of my ancestry was never given the same treatment. So I guess you shouldn't have much interest in trying to understand me, if you share my perspective. But I am not living in the 18th century; I am comfortably typing this from my keyboard. And thank God for that! Had I written this with ink on paper, I bet my handwriting would be so unintelligible that any message I would have liked to share with you would never reach you. And this internet thing is pretty cool too! It sure would have helped the witches and the seeresses, the prophets and the gurus throughout the ages get their thoughts across the lands. But somehow I feel that they seemed to have done pretty alright, despite their circumstances. I do feel an urgency in elevating myself and helping others elevate themselves, and I believe to have been incarnated in this time to help bring forth positive change, which I can now see is needed. Or else, it's looking like there won't be another century for the future generations to experience. Don't misunderstand me; I'm not claiming to be some prophet of God or someone particularly important. Not any more than you are, anyway. But I guess that's the whole point! You are so important, and the fate of humanity rests on you and me, so let's do our best. Maybe I'm just crazy. https://www.youtube.com/watch?v=kF25gN3g1Bc

So who am I then? What do I like? I am someone who spends most of my time listening to music, daydreaming. But I prefer to be awake at night. It soothes me. I can describe myself (by what I do, not who I am) as a hacker, a musician and a language enthusiast. Otherwise, I like to teach myself and be taught about strange nonsense and share it with those in my circle, which I may get around to writing about on this website. But I guess I've already started doing that with this little bit about myself. I would also like to use this site as a platform for publishing my music in the future. Stay tuned.

I have an instagram page you can follow if you want
@calleha https://instagram.com/calleha

22 May 2023, 05:40

** Mastodon
#+html: <a rel="me" href="https://mastodon.social/@calleha">@calleha@mastodon.social</a>
** YouTube
https://youtube.com/@calleha01
